### ISSUE TITLE
Add  staged dependencies 

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.rbmi#6]
# TODO

- [x] Add staged dependencies.yml
- [x] fix upstream or downstream staged dependencies.yml
  - [x]  https://github.com/insightsengineering/tern/pull/527
  - [x]  https://github.com/insightsengineering/scda.2022/pull/21
  - [x]  https://github.com/insightsengineering/scda/pull/74
  - [x] https://github.com/insightsengineering/formatters/pull/22
  - [x] https://github.com/Roche/rtables/pull/317
